// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Producer.iOS
{
	public partial class LoginVc : UIViewController
	{
		public LoginVc (IntPtr handle) : base (handle)
		{
		}
	}
}
