/* This file was generated by Settings Studio
 *
 * Copyright © 2015 Colby Williams. All Rights Reserved.
 */

namespace SettingsStudio
{

	public static class SettingsKeys
	{

		#region Visible Settings


		public const string VersionNumber = "VersionNumber";

		public const string BuildNumber = "BuildNumber";

		public const string GitCommitHash = "GitCommitHash";

		public const string TestProducer = "TestProducer";

		public const string UseLocalFunctions = "UseLocalFunctions";

		public const string LocalFunctionsUrl = "LocalFunctionsUrl";

		public const string RemoteFunctionsUrl = "RemoteFunctionsUrl";

		public const string UseLocalDocumentDb = "UseLocalDocumentDb";

		public const string LocalDocumentDbUrl = "LocalDocumentDbUrl";

		public const string RemoteDocumentDbUrl = "RemoteDocumentDbUrl";

		public const string EmbeddedSocialKey = "EmbeddedSocialKey";

		public const string UserReferenceKey = "UserReferenceKey";


		#endregion


		#region Hidden Settings


		public const string AvContentListSelectedFilter = "AvContentListFilter";

		public const string ProducerListSelectedRole = "ProducerListFilter";

		public const string LastAvContentDescription = "LastAvContentDescription";


		#endregion
	}
}